#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /config/{playbooks,.ssh} \
    /tmp/semaphore

# quietly initialise config
if [ ! -f /config/config.json ]; then
    echo "Initialising Semaphore, if the database is unreachable the container will appear unresponsive for upto 30 seconds then start spitting errors."
    semaphore-wrapper semaphore &>/dev/null
fi

# permissions
chown -R abc:abc \
    /config \
    /tmp/semaphore
