#!/usr/bin/with-contenv bash

check_var() {
    if [ -z "${!1}" ]; then
        echo "Error: No ${2} has been specified in the '${1}' variable. ${3}"
        echo "For more information, see the README: https://github.com/imagegenius/docker-semaphore#variables"
        sleep infinity
    fi
}

if [ -n "${SEMAPHORE_DB_DIALECT:-}" ] && [ "${SEMAPHORE_DB_DIALECT}" != "bolt" ]; then
#             Variable            Variable Summary
    check_var "SEMAPHORE_DB_USER" "database user"
    check_var "SEMAPHORE_DB_PASS" "database password"
    check_var "SEMAPHORE_DB_HOST" "database host"
    check_var "SEMAPHORE_DB_PORT" "database port"
    check_var "SEMAPHORE_DB"      "database name"
fi

#         Variable                          Variable Summary
check_var "SEMAPHORE_ADMIN_PASSWORD"        "admin password"
check_var "SEMAPHORE_ADMIN_NAME"            "admin name"
check_var "SEMAPHORE_ADMIN_EMAIL"           "admin email"
check_var "SEMAPHORE_ADMIN"                 "admin"
check_var "SEMAPHORE_ACCESS_KEY_ENCRYPTION" "encryption key"
